local monitor = peripheral.find("monitor")
local request = http.get ("http://worldtimeapi.org/api/ip")
local requestRep = request.readAll()
local datetimeFind = string.find(requestRep, "datetime")
print(datetimeFind)
local preDatetime = string.sub(requestRep, datetimeFind+11)
--print(preDatetime)
local datetime = string.sub(preDatetime, 1, 19)
print(datetime)
local year = string.sub(datetime, 1, 4)
print(year)
local month = string.sub(datetime, 6, 7)
print(month)
local day = string.sub(datetime, 9, 10)
print(day)
local findT = string.find(datetime, "T")
local hour = string.sub(datetime, findT, findT+2)
print(hour)
local minute = string.sub(datetime, findT+5, findT + 6)
print(minute)


