local monitor = peripheral.find("monitor")
local request = http.get ("http://worldtimeapi.org/api/ip")
local requestRep = request.readAll()
local datetimeFind = string.find(requestRep, "datetime")
print(datetimeFind)
local preDatetime = string.sub(requestRep, datetimeFind+11)
--print(preDatetime)
local datetime = string.sub(preDatetime, 1, 19)
print(datetime)
local year = string.sub(datetime, 1, 4)
print(year)
local month = string.sub(datetime, 5, 7)
print(month)
local date = string.sub(datetime, 8, 10)
print(date)
